### ISSUE TITLE
Output html encodes html/hbs instead of leaving it as is

### ISSUE THREAD

**Issue by mrmartineau** [helpers/handlebars-helper-aggregate#7]
Aggregate seems to be encoding all html in my .hbs files. How can I stop it doing that?
##### buttons.hbs:

```

---
title: Buttons

---
<a href="#" class="btn">Normal button</a>
```
##### Output:

``` html
&lt;a href=&quot;#&quot; class=&quot;btn&quot;&gt;Normal button&lt;/a&gt;
```
##### it should be:

``` html
<a href="#" class="btn">Normal button</a>
```

Used in my templates using: `{{aggregate 'styleguide/components/*.hbs'}}` & installed to devDeps..

Any ideas?

**Comment by doowb** [comment]
Have you tried using 3 curly braces instead of 2?

`{{{aggregate 'styleguide/components/*.hbs'}}}`

**Comment by mrmartineau** [comment]
Nope, gonna give it a go now. Thanks

**Comment by mrmartineau** [comment]
Thanks @doowb, your suggestion works perfectly. Should that be added to the readme?
